/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:62db9910-6ca7-44a9-9160-efc372f693c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kW9bIgCuG",
    "aws_user_pools_web_client_id": "25l4efof42o1l7t06i6vtlke26",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "jotbotchatbot_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ],
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
